
["bax_drugs_experiphrine_fnc_superBoostLocal",bax_drugs_experiphrine_fnc_superBoostLocal] call CBA_fnc_addEventHandler;
["bax_drugs_experiphrine_fnc_addExperiphrine",bax_drugs_experiphrine_fnc_addExperiphrine] call CBA_fnc_addEventHandler;
