
["bax_drugs_regenaboost_fnc_increaseRegenLocal",bax_drugs_regenaboost_fnc_increaseRegenLocal] call CBA_fnc_addEventHandler;
bax_drugs_regenaboost_defaultValue = ace_advanced_fatigue_recoveryFactor;
bax_drugs_regenaboost_amountFactors = 0;
